#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'
require_relative 'lib/grimoire'

options = { host: '127.0.0.1', port: nil }

OptionParser.new do |parser|
  parser.banner = 'Usage: grimoire --port PORT [--host HOST]'
  parser.on('--host HOST', 'Lich frontend-port host (default 127.0.0.1)') { |host| options[:host] = host }
  parser.on('--port PORT', Integer, 'Lich frontend-port port, from --detachable-client') { |port| options[:port] = port }
end.parse!(ARGV)

if options[:port].nil?
  warn 'grimoire: --port is required (the port Lich opened with --detachable-client)'
  exit 1
end

Grimoire::App.new(host: options[:host], port: options[:port]).run
